project:
  type: website
  output-dir: docs

website:
  title: "bayesian-learning-analytics"
  reader-mode: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css
    link-external-newwindow: true


execute:
  cache: true
  freeze: auto
  execute-dir: project

editor:
  render-on-save: true